### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by craftergames8** [KathleenFelth/Work-Management-Systems#1]
Hello, I am interested in your project. Could you share your database kunfiguration? And if everything works without any problems, a donation link would also be helpful so that I can donate something to you. greetings from Germany

**Comment by KathleenFelth** [comment]
Hello, im very sorry i didnt notice this message till now. The database configuration ive used is very basic. Heres an example below


	$serverName = "yourservername";
	$userName = "yourname";
	$pswd = "yourpassword";
	$dbName = "databasename";
	
	$conn = mysqli_connect('yourservername','yourname','yourpassword','databasename');
	
	if(!$conn){
		die("DB Error". mysqli_connect_error());
	}
	





> Hello, I am interested in your project. Could you share your database kunfiguration? And if everything works without any problems, a donation link would also be helpful so that I can donate something to you. greetings from Germany
